# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a04044b0f131dce03ee0ec4c7353959a5ebaa9b506efe26ac96deed3d563d32b26ac2f76a2d3595168d76e04a1e05e25a03439cee649132adff945ab8ccdbfe

test:
  secret_key_base: d39e7e39718d67bd77b7ee92f443572684cb08341c2c2a02985958fa9cb397878ec43c559376946d37aa75175653342f926bc5a04ff3d0a52cb70832d0a32180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
